// 天空之城 http://www.gepuwang.net/liuxinggepu/23066.html
export default [
    { "level": 2, "index": 6, "time": 0.5 },
    { "level": 2, "index": 7, "time": 0.5 },
    { "delay": true },
    { "level": 3, "index": 1, "time": 1.5 },
    { "level": 2, "index": 7, "time": 0.5 },
    { "level": 3, "index": 1 },
    { "level": 3, "index": 3 },
    { "delay": true },
    { "level": 2, "index": 7 },
    { "delay": true },
    { "delay": true },
    { "stop": true },

    { "level": 2, "index": 3, "time": 0.5 },
    { "level": 2, "index": 3, "time": 0.5 },
    { "delay": true },
    { "level": 2, "index": 6, "time": 1.5 },
    { "level": 2, "index": 5, "time": 0.5 },
    { "level": 2, "index": 6 },
    { "level": 3, "index": 1 },
    { "delay": true },
    { "level": 2, "index": 5 },
    { "delay": true },
    { "stop": true },

    { "level": 2, "index": 3, "time": 0.5 },
    { "level": 2, "index": 3, "time": 0.5 },
    { "delay": true },
    { "level": 2, "index": 4, "time": 1.5 },
    { "level": 2, "index": 3, "time": 0.5 },
    { "level": 2, "index": 4, "time": 0.5 },
    { "level": 3, "index": 1, "time": 1.5 },
    { "delay": true },
    { "level": 2, "index": 3 },
    { "delay": true },
    { "stop": true, "time": 0.5 },

    { "level": 3, "index": 1, "time": 0.5 },
    { "level": 3, "index": 1, "time": 0.5 },
    { "level": 3, "index": 1, "time": 0.5 },
    { "delay": true },
    { "level": 2, "index": 7, "time": 1.5 },
    { "level": 2, "index": 4, "time": 0.5 },
    { "level": 2, "index": 4 },
    { "level": 2, "index": 7 },
    { "delay": true },
    { "level": 2, "index": 7 },
    { "delay": true },
    { "stop": true },

    { "level": 2, "index": 6, "time": 0.5 },
    { "level": 2, "index": 7, "time": 0.5 },
    { "delay": true },
    { "level": 3, "index": 1, "time": 1.5 },
    { "level": 2, "index": 7, "time": 0.5 },
    { "level": 3, "index": 1 },
    { "level": 3, "index": 3 },
    { "delay": true },
    { "level": 2, "index": 7 },
    { "delay": true },
    { "stop": true },

    { "level": 2, "index": 3, "time": 0.5 },
    { "level": 2, "index": 3, "time": 0.5 },
    { "delay": true },
    { "level": 2, "index": 6, "time": 1.5 },
    { "level": 2, "index": 5, "time": 0.5 },
    { "level": 2, "index": 6 },
    { "level": 3, "index": 1 },
    { "delay": true },
    { "level": 2, "index": 5 },
    { "delay": true },
    { "delay": true },
    { "stop": true, "time": 0.5 },

    { "level": 2, "index": 3, "time": 0.5 },
    { "delay": true },
    { "level": 2, "index": 4 },
    { "level": 3, "index": 1, "time": 0.5 },
    { "level": 2, "index": 7, "time": 0.5 },
    { "level": 2, "index": 7 },
    { "level": 3, "index": 1 },
    { "delay": true },
    { "level": 3, "index": 2, "time": 0.5 },
    { "level": 3, "index": 2, "time": 0.5 },
    { "level": 3, "index": 3, "time": 0.5 },
    { "level": 3, "index": 1 },
    { "delay": true },
    { "stop": true },

    { "level": 3, "index": 1 },
    { "level": 2, "index": 7, "time": 0.5 },
    { "level": 2, "index": 6, "time": 0.5 },
    { "level": 2, "index": 6, "time": 0.5 },
    { "level": 2, "index": 7 },
    { "level": 2, "index": 5 },
    { "delay": true },
    { "level": 2, "index": 6 },
    { "delay": true },
    { "stop": true },

    { "level": 3, "index": 1, "time": 0.5 },
    { "level": 3, "index": 2, "time": 0.5 },
    { "delay": true },
    { "level": 3, "index": 3, "time": 1.5 },
    { "level": 3, "index": 2, "time": 0.5 },
    { "level": 3, "index": 3 },
    { "level": 3, "index": 5 },
    { "delay": true },
    { "level": 3, "index": 2 },
    { "delay": true },
    { "stop": true },

    { "level": 2, "index": 5, "time": 0.5 },
    { "level": 2, "index": 5, "time": 0.5 },
    { "delay": true },
    { "level": 3, "index": 1, "time": 0.5 },
    { "level": 2, "index": 7, "time": 0.5 },
    { "level": 3, "index": 1 },
    { "level": 3, "index": 3 },
    { "delay": true },
    { "level": 3, "index": 3 },
    { "delay": true },
    { "stop": true },
    { "stop": true },

    { "level": 2, "index": 6, "time": 0.5 },
    { "level": 2, "index": 7, "time": 0.5 },
    { "level": 3, "index": 1 },
    { "level": 2, "index": 7 },
    { "level": 3, "index": 2, "time": 0.5 },
    { "level": 3, "index": 2, "time": 0.5 },
    { "delay": true },
    { "level": 3, "index": 1, "time": 1.5 },
    { "level": 2, "index": 5, "time": 0.5 },
    { "level": 2, "index": 5 },
    { "delay": true },
    { "delay": true },
    { "stop": true },

    { "level": 3, "index": 4 },
    { "level": 3, "index": 3 },
    { "level": 3, "index": 2 },
    { "level": 3, "index": 1 },
    { "delay": true },
    { "level": 3, "index": 3 },
    { "delay": true },
    { "delay": true },
    { "delay": true },
    { "delay": true },
    { "level": 3, "index": 3 },
    { "delay": true },
    { "stop": true },

    { "level": 3, "index": 3 },
    { "delay": true },
    { "level": 3, "index": 6 },
    { "delay": true },
    { "level": 3, "index": 5 },
    { "level": 3, "index": 5 },
    { "delay": true },
    { "level": 3, "index": 3, "time": 0.5 },
    { "level": 3, "index": 2, "time": 0.5 },
    { "level": 3, "index": 1 },
    { "stop": true, "time": 0.5 },

    { "level": 3, "index": 1, "time": 0.5 },
    { "delay": true },
    { "level": 3, "index": 2 },
    { "level": 3, "index": 1, "time": 0.5 },
    { "level": 3, "index": 2, "time": 0.5 },
    { "level": 3, "index": 2, "time": 0.5 },
    { "level": 3, "index": 5 },
    { "delay": true },
    { "level": 3, "index": 3 },
    { "delay": true },
    { "stop": true },

    { "level": 3, "index": 3 },
    { "delay": true },
    { "level": 3, "index": 6 },
    { "delay": true },
    { "level": 3, "index": 5 },
    { "delay": true },
    { "delay": true },
    { "level": 3, "index": 3, "time": 0.5 },
    { "level": 3, "index": 2, "time": 0.5 },
    { "level": 3, "index": 1 },
    { "delay": true },
    { "stop": true, "time": 0.5 },

    { "level": 3, "index": 2 },
    { "level": 3, "index": 1, "time": 0.5 },
    { "level": 3, "index": 2, "time": 0.5 },
    { "level": 3, "index": 2, "time": 0.5 },
    { "level": 2, "index": 7 },
    { "delay": true },
    { "level": 2, "index": 6 },
    { "delay": true },
    { "stop": true },

    { "level": 2, "index": 6, "time": 0.5 },
    { "level": 2, "index": 7, "time": 0.5 },
    { "delay": true },
    { "level": 2, "index": 6 },
    { "delay": true },
    { "delay": true },
    { "delay": true }
]
